name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9.10
      run: |
        curl -L https://github.com/actions/python-versions/releases/download/3.9.10-1788162477/python-3.9.10-linux-20.04-x64.tar.gz | tar xz -C /tmp/
        sudo mv /tmp/python-3.9.10-linux-20.04-x64 /opt/python
        sudo ln -s /opt/python/bin/python3 /usr/local/bin/python
        python --version
    - name: Install requests module
      run: pip install requests
    - name: Install matplotlib module
      run: pip install matplotlib
    - name: Install pdf backend for matplotlib
      run: pip install matplotlib-backend-pdf
    - name: run File Server report
      run: python fileserverreport_pc.py
